Repository wecode-bootcamp-korea/30-1st-CaKoo-frontend, pull requests merged in 2022-03, with the labels that each got.

#4 [30기 전슬기] Add: Nav, Footer 컴포넌트 & common.scss 수정
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/styles/common.scss
Labels: Status: 수정 요청

#6 [30기 전슬기] Modify : Nav, Footer 수정 및 images 폴더 정리
  public/images/cakoo_facebook_logo_white.png
  public/images/cakoo_insta_logo_white.png
  public/images/cakoo_logo.png
  public/images/cakoo_logo_white.png
  public/images/cakoo_youtube_logo_white.png
  public/images/strawberry_biscuit_cake.jpeg
  public/img/agnes/img.png
  public/img/cos/img.png
  public/img/sophie/img.png
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: Status: Accepted

#9 [30기 김준영] Add: SignUpSuccessPage Layout & Styling
  src/pages/SignUpSuccess/SignUpSuccess.js
  src/pages/SignUpSuccess/SignUpSuccess.scss
Labels: Status: 리뷰 요청

#1 [30기 전슬기] Add : 사이즈별 filtering과 sorting
  src/pages/Main/Banner/Banner.js
  src/pages/Main/Banner/Banner.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/Product/Product.js
  src/pages/Main/Product/Product.scss
Labels: Status: 추가 기능 구현중, Status: 리뷰 요청

#5 [30기 전슬기] Add : 장바구니 담기 추가 & Fix : 조건부 렌더링 오류
  src/pages/ProductDetail/ProductAdd/ProductAdd.js
  src/pages/ProductDetail/ProductAdd/ProductAdd.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
Labels: Status: 리뷰 요청

#8 [30기 김준영] Add: Cart Product Delete Fetch
  src/pages/Cart/Button.js
  src/pages/Cart/Button.scss
  src/pages/Cart/BuyConfirm.js
  src/pages/Cart/BuyConfirm.scss
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/Product.js
  src/pages/Cart/Product.scss
  src/pages/Cart/cart.json
Labels: Status: 리뷰 요청

#7 [30기 신윤숙] "Add: Order Get Fetch Success!"
  src/Router.js
  src/pages/Order/Order.js
  src/pages/Order/Order.scss
  src/pages/Order/components/OrderInputBox.js
  src/pages/Order/components/OrderProduct.js
  src/pages/Order/components/OrderProduct.scss
  src/styles/mixin.scss
Labels: Status: 리뷰 요청

#11 [30기 김준영] Fix: Conflict
  src/Router.js
  src/components/Nav/Nav.js
  src/pages/Cart/Cart.js
  src/pages/Cart/CartProduct.js
  src/pages/Cart/CartProduct.scss
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/SignUp/Button.js
  src/pages/SignUp/Button.scss
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
  src/pages/SignUp/TextBox.js
  src/pages/SignUpSuccess/SignUpSuccess.js
  src/pages/SignUpSuccess/SignUpSuccess.scss
Labels: Status: 리뷰 요청
